### ISSUE TITLE
Небольшая доработка

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/sedona-id85318#10]
Я совсем не обратил внимания в разметке на 1 небольшой нюанс.
Заметил, что ты на главной странице логотип (в меню) сделал просто тегом `img`. Но не проверил на странице hotels.html. На главной странице так и оставляй, даже можно добавить блок див с классом лого, а на странице отелей этот див сделать ссылкой.
Получится, что на главной просто картинка, которая находится внутри блока `.logo`, и на странице отелей так же. только на странице отелей она будет еще кликабельна.

**Comment by elemeNtk0** [comment]
По тексту "Arial" — тоже исправь, чтобы Ариал был без кавычек

**Comment by elemeNtk0** [comment]
Кстати, а куда делись на главной странице подписи? http://joxi.ru/D2PBn1NUWkRqr3
Жилье, еда, сувениры. В разметке вижу, а текста нет...
Не забудь при построении сеток это исправить

**Comment by stan-devproject** [comment]
Да, про кликабельный логотип забыл — переделал.

Arial исправил, но как узнать, когда в кавычках писать, а когда без? С большой буквы или с маленькой?

Подписи добавил, забыл их)

**Comment by elemeNtk0** [comment]
Ответил ВК

**Comment by stan-devproject** [comment]
Ок, блин, написал вместо Исправлено #10 -> Исправлено №10. Хрен исправишь теперь :)

**Comment by elemeNtk0** [comment]
я уже видел) все ок
