### ISSUE TITLE
Обе страницы: не хватает .container

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/sedona-id85318#2]
`.wrapper`, это конечно круто, но нет контейнер-класса. У тебе придется для всех блоков прописывать отдельно ширину и маргины? зачем?)

**Comment by stan-devproject** [comment]
Правильно ли я понял этот issue, что вместо:

```
<div class="intro-text">
  <h1 class="intro-text-title">Седона — небольшой городок в Аризоне, заслуживающий большего!</h1>
  <span class="intro-text-features">Рассмотрим 5 причин, по которым Седона круче чем гранд каньон!</span>
</div>
```

мне писать так:

```
<div class="intro-text">
  <div class="container">
    <h1 class="intro-text-title">Седона — небольшой городок в Аризоне, заслуживающий большего!</h1>
    <span class="intro-text-features">Рассмотрим 5 причин, по которым Седона круче чем гранд каньон!</span>
  </div>
</div>
```

**Comment by stan-devproject** [comment]
Также не до конца понимаю разницу между тегами wrapper и container - или же они обычно одну и ту же функцию выполняют?

**Comment by elemeNtk0** [comment]
Слушай, я походу напутал малясь. Можно без контейнера. У тебя единый враппер, Который будет

``` css
.wrapper {
margin: 0 auto;
min-width: 768px;
max-width: 1200px;
background-color:#fff;
box-shadow: magic)))
}
```

Он и центрует и выравнивает, и резинит сам макет.

**Comment by elemeNtk0** [comment]
Аннулирую этот Ишью. Мой косяк. Привык уже, что студентам чаще удобно добавить ещё `.container`. Внутри, дабы быть уверенными (мол так на вебинарах делали)
