### ISSUE TITLE
Не злоупотребляй section+article

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/sedona-id85318#3]
Посмотри вот [это видео](https://events.yandex.ru/lib/talks/1520/).
Не стоит так часто использовать семантические теги section + article. 
На примере `feature-item`: здесь артикл лишний. Достаточно обернуть в див. У нас не такая супер уникальная часть здесь внутри блока и похожей внутри этой секции тоже нет.
Секции вполне достаточно! =) внутри див.

**Comment by stan-devproject** [comment]
Ок, видео посмотрю, а article я решил убрать и заменить на div.

**Comment by elemeNtk0** [comment]
:+1:
