### ISSUE TITLE
На обсуждение в общий чат

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/sedona-id85318#4]
``` html
<div class="icons clearfix">
   <article class="icon-item icon-house">
     <h2 class="icon-title"></h2>
     <span class="icon-text"></span>
   </article>
   <article class="icon-item icon-burger">
     <h2 class="icon-title"></h2>
     <span class="icon-text"></span>
   </article>
   <article class="icon-item icon-gift">
     <h2 class="icon-title"></h2>
     <span class="icon-text"></span>
   </article>
</div>
```

И блок по аналогии `.features-text`.

Такой блок закинь в общий чат и спроси. обсудим лучше там. Послушаем разные мнения. Но после того как ты посмотришь видео "семантика или смерть".
После своего вопроса изложи свою точку зрения. Эти теги не такие простые.
Я использую `article` очень редко. Проще написать `div` и не париться, а семантично ли это в данном контексте. 
с `section` все куда проще. они у тебя правильные.

**Comment by stan-devproject** [comment]
Ок, видео посмотрю, а article я по-убирал просто и заменил на div, потому что действительно их сложно притянуть в этом макете. 

У меня по этой позиции какой-то жесткой точки зрения нет, просто почему-то этот тег решил попробовать, так что обсуждать особо нечего.

**Comment by elemeNtk0** [comment]
Хорошо, ну потом если хочешь можем разобраться вместе. Т.к. я тоже стараюсь им не злоупотреблять
