### ISSUE TITLE
Про форму на главной

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/sedona-id85318#7]
Небольшой недочёт по поводу атрибута `value` у инпутов. Это скорее `placeholder`.т.к. Value пользователю придётся руками стирать.

Про твои сомнения могу сказать смело — не сомневайся. Разметка правильная. Редко когда приходится стилизовать саму форму, поэтому лучше использовать обёртку.

**Comment by stan-devproject** [comment]
Ок, заменил, хотя я все-таки склонен считать, что это value, которые программно задаются исходя из ближайшей, скажем, недели + возможно, по количеству людей память с прошлых заказов. 

Ибо, в placeholder скорее будет надпись "Введите здесь дату отъезда", а не конкретная дата.

**Comment by elemeNtk0** [comment]
Представь себе форму, в которой ты проверяешь не заполнено ли поле перед отправкой.
Так вот в твоём случае (когда были `value`) форма пройдёт валидацию. А пользователь даже ничего не поймёт.
Ты ввёл значения, при чем валидные, поэтому проверка отдаст TRUE. 
Форма так устроена, что placeholder — это лишь подсказка. 
Есть ещё более извращенный вариант с `value`, он для поддержки старых браузеров, но здесь лучше использовать именно `placeholder` как подсказку.

Извращенный способ:

``` html
<input type="input" value="Ваш email" 
                    onfocus="if (this.value == 'Ваш email') {this.value=''}" 
                    onBlur="if (this.value == '') {this.value='Ваш email'}">
```

Работает как placeholder, но с помощью скриптов. Что не есть круто (по текущему ТЗ сайта)

**Comment by elemeNtk0** [comment]
Закроешь ишью, как прочтёшь
