### ISSUE TITLE
Подвал сайта

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/sedona-id85318#8]
тут есть небольшой недочёт.
Скорее тебе надо сделать 3 блока (для сетки). А уже внутри добавлять контент.
Т.е. заголовок VISITSEDONA надо обернуть в `div`.

P.s. а для всех 3х блоков в футере нужен вообще 1 класс. который построит сетку) Ибо каждый блок это 1/3 от всей ширины, а элементы внутри расположены по центру блока.

**Comment by stan-devproject** [comment]
Выполнено.

**Comment by elemeNtk0** [comment]
:+1:
