### ISSUE TITLE
Отдельно по hotels.html

### ISSUE THREAD

**Issue by elemeNtk0** [stan-devproject/sedona-id85318#9]
Да, использовать `h2` можно. Просто на странице нет заголовка. СЕОшники будут ругаться. Но сюда пока не придумали ничего. 
очень спорный момент — обязателен или нет сейчас `h1`

**Comment by elemeNtk0** [comment]
Разницы между `button type "submit"` и `input type "submit"` особой нет. Единственное преимущество у баттона — его стилизовать проще. К нему можно применить `::before` и `::after`, а к инпуту нельзя. Я бы оставил баттон.

**Comment by elemeNtk0** [comment]
`form-filter` вынеси в отдельный `div`, а форму оставь без класса.

**Comment by elemeNtk0** [comment]
`hotel-item` еще не доделал? 
Что-то мало разметки) есть вопросы?

**Comment by stan-devproject** [comment]
По поводу h2: я все-таки наверно вместо section сделаю fieldset, а h2 заменю на div, чтобы у сеошников не было поводу ругаться.

Ок, form-filter вынес в отдельный div, но не будет ли потом при построении флоатной сетки форма мешать этому?

По hotel-item прошу прощения, выложил на github. Прошу проверить.

**Comment by elemeNtk0** [comment]
Про `.form-filter` не уверен, что понял тебя. Но при построении сетки там проблемы как раз возникнут, если ты уберешь класс .clearfix у формы, а Я Тебя это не просил делать)

**Comment by elemeNtk0** [comment]
По поводу `section` + `h2-h6` Можешь не переживать. Это как раз валидно и круто, если у тебя в секции есть заглавие (не h1). Это ведь отдельный блок. Чисто логически поменяв их местами — что-то изменится на странице? нет) 
Если не заострять внимания на стилях. А тупо поменять порядок этих блоков.
так что тут с сешнами и заголовками решение будет правильней. Исправь, пожалуйста)

**Comment by elemeNtk0** [comment]
.hotels-item принял.

[Небольшая подсказка по улучшению:](http://joxi.ru/KAx5ky0hwZ8dr8)
Каждый цвет → одна колонка. Т.е. сам фильтр над списком в разметке будет состоять из тех же 3х колонок, что и 3 результата ниже.
Поэтому предлагаю завести отдельные "сеточные" классы для этих элементов например (filter-column-first, filter-column-middle, filter-column-last) и чисто на них построить в будущем сетку, а на дополнительные классы типа `hotels-image` уже вешать конкретные стили оформления.

Так называемый «Модульный подход»

**Comment by stan-devproject** [comment]
По поводу section + h2-h6: Блин, но мне теперь fieldset ближе в данной верстке, может все-таки оставить их?

По .form-filter: Да, именно это я и спрашивал. Теперь понял и вернул clearfix для формы.

Ок, модульный подход сделал, но не получилось ли у меня сильное нагромождение div`ов? Можно ли делать не два дива друг в друге, а что-то типа: 

```
<div class="search-column-first hotel-image"></div>
```

**Comment by elemeNtk0** [comment]
Я про это и говорил)
Два класса надо сделать у одного дива.
Первый для кологнки задается размер и отступы (сетка)
Второй — для оформления элементов внутри

**Comment by stan-devproject** [comment]
Ок, сейчас буду переделывать :)

Плюс посмотри на блок .search-sort: я убрал там h2, чтобы сеошники не ругались + добавил ul.

**Comment by elemeNtk0** [comment]
Что-то ты стал везде убирать заголовки, так и вообще без них можно остаться. лучше верни) и в фиелдсетах верни, и фиелдсеты сделай секшнами. Это понятней. зачем тебе обнулять стили фиелдсета, когда ты можешь просто добавить новое без переопределения для секшна?

**Comment by stan-devproject** [comment]
Ок, вернул. А по fieldset`у разобрался, он не просто семантика, а еще и добавляет бордер, заменил его на section. Правда я считаю, что секции здесь все-таки не в тему.

**Comment by stan-devproject** [comment]
Прошу посмотреть + у меня в кабинете интенсива пишет, что есть замечания по графике и текстовым стилям личного проекта. Какие? Что еще надо сделать, чтобы закрыть второй и третий раздел интенсива по заданиям?

**Comment by elemeNtk0** [comment]
отправь заново на проверку по графике я еще не смотрел. Пока нет времени ближе к ночи гляну

**Comment by elemeNtk0** [comment]
Этот ишью закрываем! =)
